### ISSUE TITLE
Input filter specification and merging

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-inputfilter#1]
Now it is not possible to use input filter merging on input filters created from specification. Merging saves plenty of time when dealing with many input filters. I suppose extending `Factory` class to enable merging.

### Specification example

```php
$config = [
    'input_filter_specs' => [
         MyInput::class => [
             'foo' => [
             ],
        ],
         MyInput2::class => [
             'merge' => MyInput::class,
             'bar' => [
             ],
        ],
    ],
],
```
What is your opinion?

---

Originally posted by @vaclavvanik at https://github.com/zendframework/zend-inputfilter/issues/178

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
