### ISSUE TITLE
InputFilterInterface::getMessages() - invalid type hint

### ISSUE THREAD

**Issue by rutek** [laminas/laminas-inputfilter#27]
### Bug Report

Interface `InputFilterInterface` contains method `getMessages` with return type hint `string[]` which is invalid.

https://github.com/laminas/laminas-inputfilter/blob/78f595b6531272880cc65efa91da25d4a34246cd/src/InputFilterInterface.php#L147

`BaseInputFilter` implementing this interface returns `string[][]`, for example:

```
array(2) {
    ["field1"]=>  array(1) {
        ["isEmpty"]=> "Field is required"
    }  
    ["field2"]=>  array(1) {
        ["isEmpty"]=> "Field is required"
    }  
}
```

It's result of `BaseInputFilter:;getMessages` creating response form fields `getMessages`:

https://github.com/laminas/laminas-inputfilter/blob/78f595b6531272880cc65efa91da25d4a34246cd/src/BaseInputFilter.php#L476

As result developer using phpstan or psalm is told to implement one loop while there should be two.

**Comment by froschdesign** [comment]
@rutek 
Please have a look on the related issue report: #19
Every help is welcome! 👍

**Comment by gsteel** [comment]
No longer relevant… Fixed a pretty long time ago:

https://github.com/laminas/laminas-inputfilter/blob/2427f731e8a27cfe64cf8c9031e30973f17554be/src/InputFilterInterface.php#L179-L187
