### ISSUE TITLE
Deprecated properties in docs

### ISSUE THREAD

**Issue by rarog** [laminas/laminas-inputfilter#34]
### Bug Report

Documentation lists deprecated properties.

|    Q        |   A
|------------ | ------
| Version(s)  | 2.12.0

#### Summary

https://docs.laminas.dev/laminas-inputfilter/specs/ lists following

```php
                'allow_empty' => false,
                'continue_if_empty' => false,
```
Both properties are deprecated since 2.4.8

**Comment by froschdesign** [comment]
And also here:

* https://docs.laminas.dev/laminas-inputfilter/application-integration/usage-in-a-laminas-mvc-application/
* https://docs.laminas.dev/laminas-inputfilter/application-integration/usage-in-a-mezzio-application/

Tasks:

* Update related pages with alternative usage
* Create a migration guide

**Comment by froschdesign** [comment]
The related properties and methods are no longer deprecated:

* https://github.com/laminas/laminas-inputfilter/pull/77
* https://github.com/laminas/laminas-inputfilter/releases/tag/2.22.1
