### ISSUE TITLE
Documentation refers to non-existent alias not_empty

### ISSUE THREAD

**Issue by gennadiylitvinyuk** [laminas/laminas-inputfilter#35]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | Current documentation

#### Summary

[The documentation](https://docs.laminas.dev/laminas-inputfilter/intro/) refers to the non existent validator alias `not_empty`, `string_length`

**Comment by gennadiylitvinyuk** [comment]
There are multiple valid alternatives available.

For example for NotEmpty-Validator:

- notempty
- NotEmpty
- notEmpty

Some other documentation pages user class names...

What is now the preferred style?

**Comment by froschdesign** [comment]
@gennadiylitvinyuk 
> What is now the preferred style?

The fully qualified class name of the validators and filters. This can be checked by an IDE and provides automatic code completion.

**Comment by froschdesign** [comment]
Fixed with #36
