### ISSUE TITLE
CollectionInputFilter - isValid does not pass $context variable

### ISSUE THREAD

**Issue by vaclavvanik** [laminas/laminas-inputfilter#42]
[CollectionInputFilter::isValid($context = null)](https://github.com/laminas/laminas-inputfilter/blob/2.13.x/src/CollectionInputFilter.php#L211) does not pass $context variable to [nested input filter](https://github.com/laminas/laminas-inputfilter/blob/2.13.x/src/CollectionInputFilter.php#L240). I do not know if it is expected behavior.

I need to get whole input filter $context from my nested validators. If it is bug, I can create PR. If it is expected behavior I can create PR with new ContextCollectionInputFilter which will pass $context to nested input filter.

**Comment by froschdesign** [comment]
@vaclavvanik 
The related DocBlock contains:

https://github.com/laminas/laminas-inputfilter/blob/b6ab28b425e626b12488fec243e02d36d8dffeff/src/CollectionInputFilter.php#L209

But I don't know why it is ignored.

> If it is bug, I can create PR. If it is expected behavior I can create PR with new ContextCollectionInputFilter which will pass $context to nested input filter.

Another input filter class is not needed. Please create a pull request and update the class `Laminas\InputFilter\CollectionInputFilter` directly. The tests should show if there are any side effects.
Thanks in advance! 👍
