### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-inputfilter#44]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

PHP with [version 8.1 is released](https://www.php.net/releases/8.1/index.php) and for this component the support of the new version is still missing.

**Comment by vaclavvanik** [comment]
Inputfilter depends on laminas-filter which does not have php 8.1 support. 

Thus I think laminas-filter should be upgraded first.

**Comment by froschdesign** [comment]
@vaclavvanik 
> Thus I think laminas-filter should be upgraded first. 

Any help is welcome! 👍🏼

**Comment by weierophinney** [comment]
Completed with #48.
