### ISSUE TITLE
Removal of `container-interop/container-interop`

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-inputfilter#51]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes

#### Summary

This issue is created to keep track of the status of getting rid `container-interop` in the `laminas` components.

**Comment by settermjd** [comment]
If this hasn't been done, I'm happy to take it on.

**Comment by Ocramius** [comment]
Bumping this to latest should suffice:

https://github.com/laminas/laminas-inputfilter/blob/9d0269727615590301f467397e28e0bcfefb25e9/composer.json#L36
