### ISSUE TITLE
psr-container-stub causes Declaration incompatibile issues on using PHP preload

### ISSUE THREAD

**Issue by lampi87** [laminas/laminas-inputfilter#55]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.16.0

#### Summary

File `.psr-container-stub.php` causes problems using PHP preload because it has a more strict convetion than psr\container in version 1.1
Removing this file locally solves all related issues. E.g. see issue 23 at laminas-crypt

#### Workaround

Explicit remove file from preload files

**Comment by Ocramius** [comment]
Wait, do you preload it because it's a PHP file? It really shouldn't be done, as it isn't sources 😱

**Comment by lampi87** [comment]
I preload php files except test related stuff (subfolder test or similar)

**Comment by Ocramius** [comment]
You should only preload what is in autoload definitions in the `composer.json` files

**Comment by Ocramius** [comment]
@lampi87 btw, feel free to send a patch to rename the file to `.php.stub`, instead of `.stub.php` 👍
