### ISSUE TITLE
[BUG] Newly introduced string check for validation groups in BaseInputFilter is causing problems for CollectionFieldset with integers as Id's

### ISSUE THREAD

**Issue by wilcol** [laminas/laminas-inputfilter#58]
Since 2.16.0 there's an added string check. This check throws an exception when applying a validation group that contains integers instead of strings. The problem will occur when using a CollectionFieldset with entities that have integers as identifiers.

```
// BaseInputFilter.php
protected function validateValidationGroup(array $inputs)
  {
      foreach ($inputs as $name) {
          if (! is_string($name) || ! array_key_exists($name, $this->inputs)) {
              throw new Exception\InvalidArgumentException(sprintf(
                  'setValidationGroup() expects a list of valid input names; "%s" was not found',
                  (string) $name
              ));
          }
      }
  }
```

Solution could be to either remove the `!is_string()` check or to add an additional `is_int()` check as well `! (is_string($name) || is_int($name)) `

**Comment by Ocramius** [comment]
Before looking at solutions, we'd need a test case that shows the behavior before/after `2.16.0`.

**Comment by Ocramius** [comment]
Closing as per #60
