### ISSUE TITLE
Laminas\InputFilter\Factory::createInputFilter erroneous use of Traversable

### ISSUE THREAD

**Issue by WillyBaldy** [laminas/laminas-inputfilter#59]
### Bug Report

On version 2.16

#### Summary

Right now it's not really a bug, it's a problem with the PHPDoc that leads PHPStorm to report a problem.

> Expected parameter of type 'Laminas\InputFilter\CollectionSpecification|Laminas\InputFilter\InputFilterProviderInterface|Laminas\InputFilter\InputFilterSpecification|Traversable', 'array[]' provided

I am passing an array to `Laminas\InputFilter\Factory::createInputFilter()` and because an array doesn't really implement any of the types listed (`InputFilterSpecification|CollectionSpecification|Traversable|InputFilterProviderInterface`) it's not officially valid. 

#### Expected behavior

We should be able to pass an array without having warnings from an IDE checking for PHPDoc types. Also, this wouldn't work with multi types checking with PHP 8+. Maybe the `iterable` pseudo type would be a better type to use here, but I'm not sure.

**Comment by Ocramius** [comment]
Can you please try newer releases?

Also, can you pin to an exact code location and full error? I can't seem to find `InputFilterFactory`

**Comment by WillyBaldy** [comment]
> Can you please try newer releases?
> 
> Also, can you pin to an exact code location and full error? I can't seem to find `InputFilterFactory`

My apologies, I was using an alias for the use! I edited my "bug" report. I will try to come up with something more precise, but I just want to make sure it's clear it's not a PHP error, it's a PHPStorm "warning" based on invalid PHPDoc, it doesn't affect the code execution.

I will also try later on today newer releases for PHP 7.4, that's the version my project is at right now.

EDIT: I just checked the source of version 2.18 and problem will still be there, the same PHPDoc types are there for [createInputFilter](https://github.com/laminas/laminas-inputfilter/blob/2.18.0/src/Factory.php#L291).

**Comment by Ocramius** [comment]
The input filter specification looks OK:

https://github.com/laminas/laminas-inputfilter/blob/8c663d35926f8276b4bf1a2c571310eb285f80cb/src/Factory.php#L27

Gonna close here: the right way to reproduce this again is to create a test that shows this as a type error appearing in our `psalm-baseline.xml`, but otherwise, the specification seems correct to me.

**Comment by willy-opale** [comment]
I know this has been closed ages ago but the PHPDocs:

`\Laminas\InputFilter\CollectionSpecification|InputFilterProviderInterface|\Laminas\InputFilter\InputFilterSpecification|Traversable $inputFilterSpecification`

is still wrong  when passing an array because an array doesn't implement Traversable so it will work right now because it's just a typehint but isn't right. To prove this, just type the parameter (in argument) as Traversable and pass an array, you'll get this error:

`PHP Fatal error:  Uncaught TypeError: MyTest(): Argument #1 ($list) must be of type Traversable, array given`

**Comment by froschdesign** [comment]
@willy-opale 
The array is allowed and defined. Follow the Psalm types.

For example `InputFilterSpecification`:

https://github.com/laminas/laminas-inputfilter/blob/7ec4f709807fb3d4c34d686bc8f6b2fae47bb6fe/src/Factory.php#L285-L294

The type is imported here:

https://github.com/laminas/laminas-inputfilter/blob/7ec4f709807fb3d4c34d686bc8f6b2fae47bb6fe/src/Factory.php#L26-L33

And defined in the interface:

https://github.com/laminas/laminas-inputfilter/blob/7ec4f709807fb3d4c34d686bc8f6b2fae47bb6fe/src/InputFilterInterface.php#L14-L51

**Comment by willy-opale** [comment]
@froschdesign Thanks for taking the time for your feedback. Actually, I'm guessing my main gripe here is the heavy presence of a third party analytical tool like Psalm in your source code. By default, editors won't understand this PHPDoc and will report problems. One has to setup Psalm as a plugin in most IDE. I'm guessing that's what I'll do but it's the only project I need it for, as Symfony, Slim, Guzzle and the likes don't "depend" on Psalm the way Laminas does. Hopefully some code change will be brought to Laminas to add types to arguments, this could alleviate the "problem". Thanks again!

**Comment by froschdesign** [comment]
@willy-opale 
> By default, editors won't understand this PHPDoc and will report problems.

PHPStorm understands this by default and Visual Studio Code should also understand this, otherwise there is a plugin for it.

> Hopefully some code change will be brought to Laminas to add types to arguments, this could alleviate the "problem".

Removing the arrays in the next major version would be a better solution.

**Comment by froschdesign** [comment]
If we rely on Psalm, then this means improving the inspections and therefore the quality of the code. This is one of the building blocks on the way to delivering better and safer components for the end user.
And Psalm checks with every pull request and every update, see:

- https://github.com/marketplace/actions/laminas-continuous-integration
- https://github.com/marketplace/actions/create-ci-matrix-for-package

**Comment by willy-opale** [comment]
@froschdesign Thanks. I'm definitely not against Psalm, it's just that by default PHPStorm doesn't recognize it but recognizes PHPDoc so it reports problems. I just added the Psalm plugin, had to re-index everything but it seems to work OK now, it sees the array as being "legit". Thanks again for your time, took me almost two years to understand the root problem but better late than never 😂

**Comment by willy-opale** [comment]
> Removing the arrays in the next major version would be a better solution.

Personally, I'm not a big fan of arguments with multiple types like Laminas devs seem to love to do. You end up with code like:

```
        if ($inputFilterSpecification instanceof InputFilterProviderInterface) {
            $inputFilterSpecification = $inputFilterSpecification->getInputFilterSpecification();
        }

        if ($inputFilterSpecification instanceof Traversable) {
            $inputFilterSpecification = ArrayUtils::iteratorToArray($inputFilterSpecification);
        }

```

I personally think it's bad practice but this is very subjective of course.

**Comment by froschdesign** [comment]
> Personally, I'm not a big fan of arguments with multiple types like Laminas devs seem to love to do.
…
I personally think it's bad practice but this is very subjective of course.

No, you're wrong here. We have to deal with the code of the past, but that doesn't mean we love it!

**Comment by willy-opale** [comment]
I should have said "used to love to do" 😊
